### ISSUE TITLE
Разработка веб-интерфейса

### ISSUE THREAD

**Issue by mack1ch** [myOlimp/Frontend#2]

**Comment by F41k0m3r** [comment]
?

**Comment by mack1ch** [comment]
Это чатик

**Comment by F41k0m3r** [comment]
Зачем нам третий чат) так еще и такой неудобный

**Comment by F41k0m3r** [comment]
Попробуй кстати мне щас права на вкладку настроек выдать, ты же сделал организацию

**Comment by F41k0m3r** [comment]
В какой репозиторий мне потом коммитить, сюда или в старый?
